kind: Namespace
apiVersion: v1
metadata:
  name: tm-calculator
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tm-calculator-ingress
  namespace: tm-calculator
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tm-calculator-service
            port:
              number: 5555
---
kind: Service
apiVersion: v1
metadata:
  name: tm-calculator-service
  namespace: tm-calculator
spec:
  selector:
    app: tm-calculator
  ports:
    - port: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-calculator-deployment
  namespace: tm-calculator
  labels:
    app: tm-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-calculator
  template:
    metadata:
      labels:
        app: tm-calculator
    spec:
      containers:
      - name: tm-calculator
        image: "tomweston/tm-calculator:latest"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5555
